### ISSUE TITLE
VTMGO addon : error 'upgrade URL needed'

### ISSUE THREAD

**Issue by pborreke** [add-ons/plugin.video.vtm.go#368] opened 2023-11-03 21:10 UTC
**Describe the bug**
2023-11-03 21:46:57.148 T:9376    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh
**To Reproduce**
1.start Kodi
2.select video addons
3.click VTM GO

**Expected behavior**
A menu should come with the available posibilities for this application

**Screenshots**
Error message comes : 'please check the Kodi log'

**Logs**
2023-11-03 21:46:57.148 T:9376    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh
                                                   Traceback (most recent call last):
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\addon.py", line 186, in run
                                                       routing.run(params)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\addon.py", line 22, in index
                                                       if auth.get_tokens():
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\vtmgoauth.py", line 145, in get_tokens
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh', data={
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\util.py", line 77, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\util.py", line 184, in _request
                                                       response.raise_for_status()
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh
                                                   -->End of Python script error report<--
                                   

**System**
 - Addon version: 1.4.1
 - Kodi version: Kodi (20.2 (20.2.0) Git:20230629-5f418d0b13)
 - Inputstream adaptive version: inputstream.adaptive v20.3.14 installed
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):Windows 10 home 64-bit
 - Special Hardware (RPI / Vero4K+ / ...):

**Additional context**

**Comment by michaelarnauts** [comment] 2023-11-04 14:11
Duplicate of #366

**Closed by michaelarnauts** 2023-11-04 14:11 UTC

**Comment by pborreke** [comment] 2023-11-05 11:20
Thanks for your fast quality feedback. Indeed it works again, after installing the version 1.4.3.
