### ISSUE TITLE
Error at starting up

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/plugin.video.vtm.go#309] opened 2021-11-16 18:38 UTC
**Describe the bug**

**To Reproduce**
1. Start up kodi
2. Error appears 
3. No green dots for VTM in the grid
4. Error appears when opening a channel 
5. Error when opening a VOD program in the add 

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.
https://paste.kodi.tv/tebenaruwe
**System**
 - Addon version: 1.2.12
 - Kodi version: 19.3
 - Inputstream adaptive version: 
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): Android

**Comment by michaelarnauts** [comment] 2021-11-25 17:59
This is also a duplicate of https://github.com/add-ons/plugin.video.vtm.go/issues/296

**Closed by michaelarnauts** 2021-11-25 17:59 UTC
