### ISSUE TITLE
Black screen when starting stream and during commercials.

### ISSUE THREAD

**Issue by keiem** [add-ons/plugin.video.vtm.go#238] opened 2020-11-23 14:20 UTC
**Describe the bug**
When starting a stream, the screen turn's black for 1 a 2 seconds.  The same occurs just before a commercial and in the commercial.

**To Reproduce**
Just starting a stream, no other actions involved.

**Expected behavior**
A stream that starts without hick-ups during the complete length of the stream.

**Screenshots**
N/A

**System**
 - Addon version: 1.2.0
 - Kodi version:18.9.0
 - Inputstream adaptive version: 2.4.6.1
 - Operating System: CoreElec
 - Special Hardware: Khadas VIM1

**Additional context**
No

**Comment by michaelarnauts** [comment] 2020-11-24 12:22
Duplicate of #139

**Closed by michaelarnauts** 2020-11-24 12:22 UTC
