### ISSUE TITLE
VTMGo - No content available

### ISSUE THREAD

**Issue by PeterCloet** [add-ons/plugin.video.vtm.go#367] opened 2023-11-03 08:31 UTC
**Describe the bug**
As soon as I open VTMGo, Kodi triggers an error and refers to the log.

**To Reproduce**
1. Go to VTMGo
2. Open add-on
3. No content available from menu

**Expected behavior**
N/A

**Screenshots**
N/A

**Logs**
https://paste.kodi.tv/agidehixiq.kodi

**System**
 - Addon version: 1.4.2+matrix.1
 - Kodi version: 19.4
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec 10.0.2
 - Special Hardware (RPI / Vero4K+ / ...): Rpi4

**Additional context**

**Comment by peno64** [comment] 2023-11-03 09:39
I think this is the same as #366

**Comment by michaelarnauts** [comment] 2023-11-04 14:10
Duplicate of #366

**Closed by michaelarnauts** 2023-11-04 14:10 UTC
