### ISSUE TITLE
Playback of video on demand streams isn't working

### ISSUE THREAD

**Issue by michaelarnauts** [add-ons/plugin.video.vtm.go#241] opened 2020-12-03 07:52 UTC
## Issue description
**Describe the bug**
The playback of video on demand streams isn't working anymore due to a change at VTM that Inputstream Adaptive isn't handling correctly. You can see in the log that it is trying to download a segment at `https://dcs-vod.apis.anvato.net/vod/p/session/https://dcs-jite.cdn.anvato.net/prod/v97/media/4D7ACFAA6F654F40999164950F4ABE37/4200000/fmp4-init-video.mp4`. 

There is an open PR at Inputstream Adaptive to fix this at https://github.com/peak3d/inputstream.adaptive/pull/566 (Leia)
and https://github.com/peak3d/inputstream.adaptive/pull/565 (Matrix).

## Workaround

There is a workaround for this issue by installing this zip that uses an embedded proxy to modify the MPEG DASH Manifest so Inputstream Adaptive works. 

Builds with workaround:
* [plugin.video.vtm.go-1.2.1-manifest-proxy-e7739cc.zip](https://github.com/add-ons/plugin.video.vtm.go/files/5747493/plugin.video.vtm.go-1.2.1-manifest-proxy-e7739cc.zip) (Kodi 18)
* [plugin.video.vtm.go-1.2.1+matrix.1-manifest-proxy-e7739cc.zip](https://github.com/add-ons/plugin.video.vtm.go/files/5747494/plugin.video.vtm.go-1.2.1%2Bmatrix.1-manifest-proxy-e7739cc.zip) (Kodi 19)

| Platform       | Kodi 18 | Kodi 19 |
| -------------- | ------- | ------- |
| Windows x64    | Tested     |         |
| Linux x64      | Tested     |         |
| Android        | Tested     |         |

## Compiled Inputstream Adaptive with correct Fix

You can also try installing a compiled version of Inputstream Adaptive with this fix:

| Platform | Kodi 18 (Leia) | Kodi 19 (Matrix) |
| ------------- | -------------- | ---------------- |
| Windows x64   | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5643062/inputstream.adaptive_baseurl_kodi18_leia_windows_x64.zip) | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5643061/inputstream.adaptive_baseurl_kodi19_matrix_windows_x64.zip)
| Linux x64     | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5641497/inputstream.adaptive_baseurl_kodi18_leia_linux_x64.zip) | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5641498/inputstream.adaptive_baseurl_kodi19_matrix_linux_x64.zip)
| Raspberry Pi 3+4  | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5661532/inputstream.adaptive-rpi-3-4-Leia-2.4.6.1a.zip) | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5684575/inputstream.adaptive-rpi-3-4-Matrix.zip)
| Android arm7  | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5664345/inputstream.adaptive-android-armv7-Leia-2.4.6.zip) | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5715531/android-armv7-matrix-v2.0.10-547-g174ab59.zip)
| Android arm8  | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5661535/inputstream.adaptive-android-armv8-Leia-2.4.6.zip) | [Download](https://github.com/add-ons/plugin.video.vtm.go/files/5715530/android-aarch64-matrix-v2.0.10-547-g174ab59.zip)
| OSMC (Vero4K+)| [Download .deb](https://github.com/michaelarnauts/inputstream.adaptive/raw/20201218-vero4k-osmc/vero3-mediacenter-osmc.deb)  |  |
| OSMC (RPI 3+4)| [Download .deb](https://github.com/michaelarnauts/inputstream.adaptive/raw/20201218-vero4k-osmc/rbp4-mediacenter-osmc.deb)  |  |

> Note: For OSMC, you'll need to install the debian package with `sudo dpkg -i vero3-mediacenter-osmc.deb`.

> Note: For Matrix, you need a build later then 23th November.

Thanks to @mediaminister and @peno64 for the builds!

**Comment by michaelarnauts** [comment] 2020-12-03 08:20
[kodi.log](https://github.com/add-ons/plugin.video.vtm.go/files/5634613/kodi.log)

**Comment by michaelarnauts** [comment] 2020-12-03 10:40
I've opened an upstream PR at https://github.com/peak3d/inputstream.adaptive/pull/565

**Comment by dagwieers** [comment] 2020-12-03 13:06
Once this gets approved we will have to assemble all stakeholders to get a new release tested and released.
This may take some time to get fixed, temporary builds could be made available for various platforms.
But an official release of **inputstream.adaptive** for Leia may take days, if not weeks :-/

**Comment by michaelarnauts** [comment] 2020-12-03 13:39
One possible workaround (I think the Netflix addon is doing this), is to proxy the manifest, and modify it so it works with what inputstream adaptive understands. I would rather not do this, but if a new release of inputstream adaptive is not possible in Leia, this might be our only solution to fix this in Leia.

**Comment by michaelarnauts** [comment] 2020-12-04 13:40
I've added compiled versions for linux and windows of the updated inputstream to the issue above.
Thanks to @mediaminister for the compile.

**Comment by peterdekker** [comment] 2020-12-04 14:12
Thanks! Can I just install the updated Inputstream Adaptive package zip via the normal visual package installation in Kodi? Or do I have to follow extra steps, like removing an old version?

**Comment by abanink** [comment] 2020-12-04 15:13
installed inputstream.adaptive_baseurl_kodi18_leia_linux_x64.zip  from zip file (have to allow it in kodi)
I had to restart kodi before it worked again.

Thanks a bunch Michael

**Comment by davidbe** [comment] 2020-12-04 15:23
Can a arm-version be compiled (for Raspberry Pi 3 :-) )? Or is it easy enough to do it by myself?

**Comment by timtilburgs** [comment] 2020-12-04 15:25
> I've added compiled versions for linux and windows of the updated inputstream to the issue above.
> Thanks to @mediaminister for the compile.
Is there a version for raspberry pi available?

**Comment by mediaminister** [comment] 2020-12-04 16:43
You can build inputstream adaptive for raspberry pi with raspbian os on raspberry pi hardware.

```
sudo apt install autoconf bison build-essential curl default-jdk gawk git gperf libcurl4-openssl-dev zlib1g-dev cmake zip

cd folder # folder where you want to build everything

git clone https://github.com/raspberrypi/tools --depth=1
git clone https://github.com/raspberrypi/firmware --depth=1
```
**Getting Kodi and Inputstream Adaptive sources:**

For Kodi 18 Leia:

```
git clone -b Leia https://github.com/xbmc/xbmc.git
git clone -b leia-base-url-in-adaptionset https://github.com/michaelarnauts/inputstream.adaptive.git
```

For Kodi 19 Matrix:

```
git clone -b master https://github.com/xbmc/xbmc.git
git clone -b matrix-base-url-in-adaptionset https://github.com/michaelarnauts/inputstream.adaptive.git
```
**Building InputStream Adaptive**
´´´
cd inputstream.adaptive && mkdir build && cd build
cmake -DADDONS_TO_BUILD=inputstream.adaptive -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
make
cd ../../xbmc/addons/
zip -r /tmp/inputstream.adaptive.zip inputstream.adaptive
```

This will create inputstream.adaptive.zip in the /tmp folder

**Comment by peno64** [comment] 2020-12-04 20:31
I am compiling this now.
Can take some time however...

**Comment by peno64** [comment] 2020-12-04 21:56
For Leia (don't use it for Matrix!), the version is now available at following location:
http://users.telenet.be/peno/kodi/addons/inputstream.adaptive

Install this zip via the kodi addon installer from zip and restart the pi
I tested VTM go and it works fine with it.

For Matrix it doesn't work at this moment. kodi just crashes... I am recompiling everything again from scratch to see if it then works...

**Comment by michaelarnauts** [comment] 2020-12-04 22:36
@peno64 thanks! I'll add your zip it to the issue post later. I think you need a pretty recent Kodi Matrix for things to work. After 23 November according to mediaminister.

**Comment by peno64** [comment] 2020-12-04 22:46
@michaelarnauts 
Unfortunately it doesn't work for Matrix.
When I install this compiled version (your version does compile succesfully against matrix) and play something that uses inputstream.adaptive (not only vtm go), kodi just crashes and restarts.
I am a bit afraid that the matrix code is still evolving too much and that your branch of inputstream.adaptipe for matrix is already too old...

I am trying now to compile the standard inputstream.adaptive if that works.

And I am using the latest Matrix build from today...

**Comment by peno64** [comment] 2020-12-04 23:08
hm, also the standard recompiled inputstream.adaptive (master) crashes on matrix...

**Comment by mediaminister** [comment] 2020-12-05 05:11
You need a Kodi Matrix nightly build from 23 November or later for this to work! https://github.com/xbmc/xbmc/pull/18809#issuecomment-731713820

**Comment by peno64** [comment] 2020-12-05 07:18
I am using the latest from https://test.libreelec.tv/ (LibreELEC-RPi4.arm-9.80-nightly-20201204-387f119.tar)
This is the crash log: https://paste.kodi.tv/zufawodado.kodi

**Comment by mediaminister** [comment] 2020-12-05 10:07
Okay, the crash happens because LibreELEC uses the Kodi 19.0b1-Matrix package in their nightly builds and this beta package was released before this issue was fixed on 23 November.

To fix the crash on LibreELEC, you need a build that uses a newer Kodi package.

https://github.com/LibreELEC/LibreELEC.tv/commit/1a55573c227f69616d6361eb4e6baa7b87cbc296#diff-21d81d796fedce2e4895543ec08aa245e3927eee289bdde6cd091c0bb2a64201

You need at least https://github.com/xbmc/xbmc/archive/34fe42353f0b1f6c638954dae66e9af3ba73d332.tar.gz

I guess this can be fixed by updating `PKG_VERSION` and `PKG_SHA256` in https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/package.mk and compiling LibreELEC yourself.

**Comment by peno64** [comment] 2020-12-05 11:45
Well... I think we will gonna wait until libreelec updates its package...
At least we know the reason now.

**Comment by peterdekker** [comment] 2020-12-05 12:52
> For Leia (don't use it for Matrix!), the version is now available at following location:
> http://users.telenet.be/peno/kodi/addons/inputstream.adaptive
> 
> Install this zip via the kodi addon installer from zip and restart the pi
> I tested VTM go and it works fine with it.
> 
> For Matrix it doesn't work at this moment. kodi just crashes... I am recompiling everything again from scratch to see if it then works...

I can confirm that this fix works for Kodi Leia on Raspbery Pi 3 (LibreElec). Thanks!

**Comment by pl0ng** [comment] 2020-12-05 13:36
Tried the Leia Linux x64 build on OSMC Vero4K. Installs fine, but streams keep showing errors.

**Comment by michaelarnauts** [comment] 2020-12-05 13:58
> Tried the Leia Linux x64 build on OSMC Vero4K. Installs fine, but streams don't play and throw errors.

OSMC uses a different build-process. I'll try building a package later today.

**Comment by timtilburgs** [comment] 2020-12-05 15:10
> > For Leia (don't use it for Matrix!), the version is now available at following location:
> > http://users.telenet.be/peno/kodi/addons/inputstream.adaptive
> > Install this zip via the kodi addon installer from zip and restart the pi
> > I tested VTM go and it works fine with it.
> > For Matrix it doesn't work at this moment. kodi just crashes... I am recompiling everything again from scratch to see if it then works...
> 
> I can confirm that this fix works for Kodi Leia on Raspbery Pi 3 (LibreElec). Thanks!

It 's also working fine on rpi4

**Comment by frankdpGH** [comment] 2020-12-05 22:05
Hi, What about Android? Have actually Leia and Inputstream Adaptive 2.4.6 on Android TV and TV Box. VOD stopped working.

**Comment by pl0ng** [comment] 2020-12-06 10:51
> > Tried the Leia Linux x64 build on OSMC Vero4K. Installs fine, but streams don't play and throw errors.
> 
> OSMC uses a different build-process. I'll try building a package later today.

Thanks in advance

**Comment by peno64** [comment] 2020-12-06 20:54
Under http://users.telenet.be/peno/kodi/addons/inputstream.adaptive there is now also an android version of the new inputstream.adaptive which fixes the vtm go problem

**Comment by pl0ng** [comment] 2020-12-07 20:07
@michaelarnauts , please don't take this in a negative/pushy way, but if you could build the osmc package, I'd really appreciate it. Also, keeps the gf from nagging. Thanks :-)

**Comment by frankdpGH** [comment] 2020-12-08 07:23
> Under http://users.telenet.be/peno/kodi/addons/inputstream.adaptive there is now also an android version of the new inputstream.adaptive which fixes the vtm go problem



> Under http://users.telenet.be/peno/kodi/addons/inputstream.adaptive there is now also an android version of the new inputstream.adaptive which fixes the vtm go problem

Thanks ! Working perfect on android ARM8. On ARM7 : "Invalid structure".

**Comment by peno64** [comment] 2020-12-08 09:55
@frankdpGH 
arm7 is 32 bit, arm8 is 64 bit. So it doesn't wunder met at all that you get this kind of error.

**Comment by peno64** [comment] 2020-12-08 12:03
@frankdpGH 
Under http://users.telenet.be/peno/kodi/addons/inputstream.adaptive/tobetested there is an armv7 android version but since I do not have such a system, it is untested and to be used at your own risk if it work.
The worst that can happen is that it does not work and that you have to revert to the standard inputstream.adaptive version again I guess but no guarantees.

**Comment by peno64** [comment] 2020-12-08 12:05
@frankdpGH
Now since you already tried the armv8 version on your armv7 system, it can get only better with this version I guess. It wasn't working anyway anymore because of that...

**Comment by frankdpGH** [comment] 2020-12-08 12:38
> @frankdpGH
> Now since you already tried the armv8 version on your armv7 system, it can get only better with this version I guess. It wasn't working anyway anymore because of that...
@peno64 
Thanks a lot! Just tested the v7 and it's working. Just had once a missed sound sync when jumping forward but this is not abnormal. Thank you all for providing this!!

**Comment by michaelarnauts** [comment] 2020-12-08 14:41
Okay. That leaves just osmc, but I tried compiling yesterday (and you have to build a full osmc-mediacenter package, that takes a while in my laptop) but I got some compilation errors. This will take some time...

**Comment by ghluhi** [comment] 2020-12-08 22:29
> 
> 
> @frankdpGH
> arm7 is 32 bit, arm8 is 64 bit. So it doesn't surprise me at all that you get this kind of error.

I have tried installing the arm7 32bit version on a Sony KD43XE8099 and get the same "Invalid structure" error. However, when checking the contents of the .zip file, it seems the zip file structure is corrupt. Something wrong seems to have happened while packing the data. BTW, thanks to all people working hard to fix this!

**Comment by peno64** [comment] 2020-12-09 07:58
@ghluhi  , @frankdpGH  , @michaelarnauts 

You are right, the uploaded file inputstream.adaptive-android-armv7-Leia-2.4.6 was truncated...
I uploaded and downloaded it again and now it is ok.

**Comment by peno64** [comment] 2020-12-09 08:02
[inputstream.adaptive-android-armv7-Leia-2.4.6.zip](https://github.com/add-ons/plugin.video.vtm.go/files/5664345/inputstream.adaptive-android-armv7-Leia-2.4.6.zip)

This is the correct file for armv7

**Comment by ghluhi** [comment] 2020-12-09 10:00
> 
> 
> [inputstream.adaptive-android-armv7-Leia-2.4.6.zip](https://github.com/add-ons/plugin.video.vtm.go/files/5664345/inputstream.adaptive-android-armv7-Leia-2.4.6.zip)
> 
> This is the correct file for armv7

This version installs correctly. I tested it briefly using VTM.GO. Playing works but still has some issues:
- playing works untils it hits a commercial break; then it just jumps back to the start of the VOD but plays again with no more sound
- FFing beyond the commerical break also loses sound
- when playing (normal speed) beyond a commercial break (after first FFing into the commercial break), stopping and then restarting the VOD from that point in time, again no more sound

However this is a big step forward from not being able to see anything. Thank you for that!

These issues have been a regular problem for me, although previously I did not lose sound, but I had issues with positioning and subtitles beyond commercial breaks. Following the discussons online, I understand these can only be solved completely in the Kodi Matrix versions. Did I understand this correctly?

**Comment by FredericMa** [comment] 2020-12-09 12:57
> * playing works untils it hits a commercial break; then it just jumps back to the start of the VOD but plays again with no more sound

I experienced the same problem.
Although I didn't had any sound issues after FFing.

**Comment by lovecrafthowardphillips** [comment] 2020-12-10 11:59
> > [inputstream.adaptive-android-armv7-Leia-2.4.6.zip](https://github.com/add-ons/plugin.video.vtm.go/files/5664345/inputstream.adaptive-android-armv7-Leia-2.4.6.zip)
> > This is the correct file for armv7
> 
> This version installs correctly. I tested it briefly using VTM.GO. Playing works but still has some issues:
> 
> * playing works untils it hits a commercial break; then it just jumps back to the start of the VOD but plays again with no more sound
> * FFing beyond the commerical break also loses sound
> * when playing (normal speed) beyond a commercial break (after first FFing into the commercial break), stopping and then restarting the VOD from that point in time, again no more sound
> 
> However this is a big step forward from not being able to see anything. Thank you for that!
> 
> These issues have been a regular problem for me, although previously I did not lose sound, but I had issues with positioning and subtitles beyond commercial breaks. Following the discussons online, I understand these can only be solved completely in the Kodi Matrix versions. Did I understand this correctly?

Experiencing the same issues using Kodi 18.9 on Android 9.

**Comment by keiem** [comment] 2020-12-12 17:07
We have the problem after this fix that the speed of the stream is not constant, it speeds up and slows down the whole time.

I installed the rpi version on my khadas Vim.  i assume the rpi version is linux-arm and the linux-x64 package is for 64 bit amd en intel processors?

**Comment by peno64** [comment] 2020-12-12 19:37
I played all episodes from Ninjago for my kid and I have no problem at all.

**Comment by lovecrafthowardphillips** [comment] 2020-12-12 21:01
> I played all episodes from Ninjago for my kid and I have no problem at all.

I would assume there are no commercial breaks in those Ninjago episodes? If so that would explain why you didn't experience any problems.

**Comment by peno64** [comment] 2020-12-12 21:08
@lovecrafthowardphillips 

Yes there are. Which is strange because I thought that this is not allowed in childerens programs, but in every episode of 11 minutes there is a commercial break.

**Comment by keiem** [comment] 2020-12-13 11:27
If I remeber correctly it was Dara, episode 126.  When I played it on my PC with chrome, it had the same behaviour.

**Comment by michaelarnauts** [comment] 2020-12-13 12:28
Update: Added link to IA for Matrix on RPI 3/4.

**Comment by michaelarnauts** [comment] 2020-12-13 12:29
Also, the Matrix-patch has been merged in IA, the Leia-patch is still open. You can follow the progress here: https://github.com/peak3d/inputstream.adaptive/pull/566

**Comment by pl0ng** [comment] 2020-12-17 11:51
@michaelarnauts , do you possibly have a planning/eta on the osmc fix? Thanks

**Comment by michaelarnauts** [comment] 2020-12-17 19:39
I'm sorry, I can't give an ETA since I don't have a solution yet to be able to build.

You could try the following, it might work...

* Replace the file in `/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.4.5` with one from the rpi zip (you'll need to rename the 2.4.6 from the zip to the existing file on your system). The other files are symlinks, so you need to use the exact same filename.
* Also replace the `libssd_wv.so`. Or not, maybe try first without replacing.
* Make sure you reboot before testing.

Also, backup the original file in case it doesn't work so you can rollback.

No guarantees, I actually think it won't work, but since the architecture matches, it might just work.

**Comment by michaelarnauts** [comment] 2020-12-18 12:03
@pl0ng I think I've managed to make a build for OSMC for the Vero4K+. Can you test if it works?

You can download the .deb file at https://github.com/michaelarnauts/inputstream.adaptive/raw/20201218-vero4k-osmc/vero3-mediacenter-osmc.deb

Copy it to your device, and install with with `sudo dpkg -i vero3-mediacenter-osmc.deb`, and restart your device.

**Comment by pl0ng** [comment] 2020-12-18 19:17
@michaelarnauts , appreciate your work!
However, my system throws the same inputstream adaptive error as before (Leie, Vero4K)

**Comment by michaelarnauts** [comment] 2020-12-18 19:28
> @michaelarnauts , appreciate your work!
> However, my system throws the same inputstream adaptive error as before (Leia, Vero4K)

Hmm, you are sure the Debian package was installed correctly? Can you verify the date of the installed files? Did you also make sure you have rebooted before trying?

**Comment by michaelarnauts** [comment] 2020-12-18 19:42
It should look like this:
```
# wget https://github.com/michaelarnauts/inputstream.adaptive/raw/20201218-vero4k-osmc/vero3-mediacenter-osmc.deb
# dpkg -i vero3-mediacenter-osmc.deb
# ls -lah /usr/lib/kodi/addons/inputstream.adaptive/
total 2,8M
drwxr-xr-x  2 root root 4,0K dec 18 20:39 .
drwxr-xr-x 68 root root 4,0K dec 18 20:39 ..
lrwxrwxrwx  1 root root   28 dec 18 10:23 inputstream.adaptive.so -> inputstream.adaptive.so.18.9
lrwxrwxrwx  1 root root   29 dec 18 10:23 inputstream.adaptive.so.18.9 -> inputstream.adaptive.so.2.4.6
-rw-r--r--  1 root root 1,9M dec 18 10:23 inputstream.adaptive.so.2.4.6
-rw-r--r--  1 root root 862K dec 18 10:21 libssd_wv.so
```

I haven't tried the package on my Vero4K+ yet, since it isn't connected to a screen anymore at the moment. I have moved over to the new Google Chromecast.

**Comment by michaelarnauts** [comment] 2020-12-18 19:43
I've also compiled a version for OSMC on the RPI in case somebody is interested. Please let me know if it works.

**Comment by ThrowsThrowable** [comment] 2020-12-19 07:57
> It should look like this:
> 
> ```
> # wget https://github.com/michaelarnauts/inputstream.adaptive/raw/20201218-vero4k-osmc/vero3-mediacenter-osmc.deb
> # dpkg -i vero3-mediacenter-osmc.deb
> # ls -lah /usr/lib/kodi/addons/inputstream.adaptive/
> total 2,8M
> drwxr-xr-x  2 root root 4,0K dec 18 20:39 .
> drwxr-xr-x 68 root root 4,0K dec 18 20:39 ..
> lrwxrwxrwx  1 root root   28 dec 18 10:23 inputstream.adaptive.so -> inputstream.adaptive.so.18.9
> lrwxrwxrwx  1 root root   29 dec 18 10:23 inputstream.adaptive.so.18.9 -> inputstream.adaptive.so.2.4.6
> -rw-r--r--  1 root root 1,9M dec 18 10:23 inputstream.adaptive.so.2.4.6
> -rw-r--r--  1 root root 862K dec 18 10:21 libssd_wv.so
> ```
> 
> I haven't tried the package on my Vero4K+ yet, since it isn't connected to a screen anymore at the moment. I have moved over to the new Google ChromecaLooks the same on my vero4k+, but still having the same errors as before like @pl0ng.

> It should look like this:
> 
> ```
> # wget https://github.com/michaelarnauts/inputstream.adaptive/raw/20201218-vero4k-osmc/vero3-mediacenter-osmc.deb
> # dpkg -i vero3-mediacenter-osmc.deb
> # ls -lah /usr/lib/kodi/addons/inputstream.adaptive/
> total 2,8M
> drwxr-xr-x  2 root root 4,0K dec 18 20:39 .
> drwxr-xr-x 68 root root 4,0K dec 18 20:39 ..
> lrwxrwxrwx  1 root root   28 dec 18 10:23 inputstream.adaptive.so -> inputstream.adaptive.so.18.9
> lrwxrwxrwx  1 root root   29 dec 18 10:23 inputstream.adaptive.so.18.9 -> inputstream.adaptive.so.2.4.6
> -rw-r--r--  1 root root 1,9M dec 18 10:23 inputstream.adaptive.so.2.4.6
> -rw-r--r--  1 root root 862K dec 18 10:21 libssd_wv.so
> ```
> 
> I haven't tried the package on my Vero4K+ yet, since it isn't connected to a screen anymore at the moment. I have moved over to the new Google Chromecast.

Looks the same on my vero4k+, but still having the same errors as before like @pl0ng.
Thanks for the effort!

**Comment by pl0ng** [comment] 2020-12-19 08:36
Can confirm same as @ThrowsThrowable .
Timestamps are as depicted in your post @michaelarnauts . Did a reboot after installing the deb.

**Comment by dwalerXIII** [comment] 2020-12-26 11:22
for osmc on rpi 3 I get this message:
dpkg: betreffende rbp4-mediacenter-osmc.deb dat rbp4-mediacenter-osmc bevat:
 rbp2-mediacenter-osmc is in strijd met xbmc
  rbp4-mediacenter-osmc levert xbmc en moet geïnstalleerd worden.

dpkg: fout bij verwerken van archief rbp4-mediacenter-osmc.deb (--install):
 conflicterende pakketten - rbp4-mediacenter-osmc wordt niet geïnstalleerd
Fouten gevonden tijdens verwerken van:
 rbp4-mediacenter-osmc.deb

**Comment by michaelarnauts** [comment] 2020-12-27 15:24
While the fix for Inputstream Adaptive is the correct way to solve this, it takes **waaaaay** to much time for the developer of Inputstream Adaptive to accept the patch and make a new release.

I've went for a different approach, and tried to modify the Manifest on the fly so it's accepted by Inputstream Adaptive. It should work with both the fixed Inputstream Adaptive, and the current released version.

You can download a zip here: https://github.com/add-ons/plugin.video.vtm.go/archive/manifest-proxy.zip (Leia only for now, sorry)

Please feel free to test this out, and report if it's working or not. It's not fully tested on my system.

**Comment by a1ad** [comment] 2020-12-28 10:26
@michaelarnauts Nice!, it is working great here. Are you going to release something like this for the Streamz plugin?

**Comment by michaelarnauts** [comment] 2020-12-28 10:32
> @michaelarnauts Nice!, it is working great here. Are you going to release something like this for the Streamz plugin?

Yep, that's the plan. I first want to have some more testing, so of you have multiple systems (windows, Linux, Android) feel free to test and report back.

What system have you tried on?

**Comment by a1ad** [comment] 2020-12-28 10:59
> > @michaelarnauts Nice!, it is working great here. Are you going to release something like this for the Streamz plugin?
> 
> Yep, that's the plan. I first want to have some more testing, so of you have multiple systems (windows, Linux, Android) feel free to test and report back.
> 
> What system have you tried on?

LibreELEC 9.2.6, going to test it on a Kodi install on Fedora later in the day.

**Comment by dirkronsmans** [comment] 2020-12-28 11:16
Just tested on CoreElec 9.2.5 (on Odroid N2)

Movies and TV shows seems to work fine
Kids stuff has some issues. The advertisement plays but then it just goes back to the menu. Same show works fine on through a browser. (e.g. Zeppe & Zikki ep 1)

**Comment by michaelarnauts** [comment] 2020-12-28 11:22
> Just tested on CoreElec 9.2.5 (on Odroid N2)
> 
> Movies and TV shows seems to work fine
> Kids stuff has some issues. The advertisement plays but then it just goes back to the menu. Same show works fine on through a browser. (e.g. Zeppe & Zikki ep 1)

Hmm, I can confirm. I'll look into this.

**Comment by michaelarnauts** [comment] 2020-12-28 11:29
It seems that the Kids shows (or at least Zeppe & Zikke S01E01) is still using the `SegmentLists`, so that doesn't need the workaround. It will work for now if you disable the option in the expert settings to not use the proxy.

I'll modify this so it will work anyway and doesn't rewrite the manifest in these cases.

**Comment by michaelarnauts** [comment] 2020-12-28 13:48
Builds with workaround:
* [plugin.video.vtm.go-1.2.1-manifest-proxy-e7739cc.zip](https://github.com/add-ons/plugin.video.vtm.go/files/5747493/plugin.video.vtm.go-1.2.1-manifest-proxy-e7739cc.zip)
* [plugin.video.vtm.go-1.2.1+matrix.1-manifest-proxy-e7739cc.zip](https://github.com/add-ons/plugin.video.vtm.go/files/5747494/plugin.video.vtm.go-1.2.1%2Bmatrix.1-manifest-proxy-e7739cc.zip)

**Comment by michaelarnauts** [comment] 2020-12-28 13:49
Somebody using Kodi 19 and willing to test the latest builds (see post above)? The issue with the Kids-streams is fixed in this version.

**Comment by a1ad** [comment] 2020-12-28 14:42
Its working on 18, also the kids stuff

**Comment by cometoluc** [comment] 2020-12-28 22:58
Hello, i am new here and have a question about the latest VGMGO addon fchrome
approximatly a month ago when the newest version of vgmgo came i had the problem that nothing would stream. I am not a great programmer so my question
I work on a pc core I5 with windows 7 pro 32bit  for kodi to see all series and so on and the addon VTMGO witch was always working fine

my version of kodi is  Kodi:18.7 Gir:20200520-f147a84e3
my chrome verstion is the latest

Can anybody here explain me what i have to do to get it going again please? Remember i am a amateur

**Comment by michaelarnauts** [comment] 2020-12-29 07:11
> Hello, i am new here and have a question about the latest VGMGO addon fchrome
> approximatly a month ago when the newest version of vgmgo came i had the problem that nothing would stream. I am not a great programmer so my question
> I work on a pc core I5 with windows 7 pro 32bit for kodi to see all series and so on and the addon VTMGO witch was always working fine
> 
> my version of kodi is Kodi:18.7 Gir:20200520-f147a84e3
> my chrome verstion is the latest
> 
> Can anybody here explain me what i have to do to get it going again please? Remember i am a amateur

You need to install the zip from https://github.com/add-ons/plugin.video.vtm.go/files/5747493/plugin.video.vtm.go-1.2.1-manifest-proxy-e7739cc.zip in Kodi. Use install by zip under Add-ons. This should fix the issue. A new release will be made soon.

**Comment by peno64** [comment] 2020-12-29 08:26
@michaelarnauts 
I installed it on a fresh new card with the latest nightly build on a rpi4 under libreelec and when installing I get the message "failed to find dependency inputstream.adaptive". So I first installed inputstream.adaptive manually via the search in kodi. The proposed versions are 2.6.4.1, 2.6.6.1 and 2.6.6.2. I installed the last. 
I see in adon.xml of the zip plugin.video.vtm.go-1.2.1+matrix.1-manifest-proxy-e7739cc.zip that it refers to:
<import addon="inputstream.adaptive" version="2.4.3"/>
So that should be changed for Matrix.
Then I installed VTM GO again and now it installed fine ( version 1.2.1+matrix.1).

Playing a movie worked only one time. Almost always it just stalls after the first commercial. This for kids and adult movies. Pausing, going a bit  backward or foreward, nothing helps.
Then I installed inputstream.adaptive-rpi-3-4-Matrix.zip, your fixed inputstream.adaptive and rebooted but that does not help at all.

Then I installed version plugin.video.vtm.go-1.2.0+matrix.1.zip
Still with the patched inputstream.adaptive I try this version but still the same problem.

**Comment by peno64** [comment] 2020-12-29 08:45
@michaelarnauts 
I installed it on a fresh new latest nightly build on windows and here everything just went fine...
No problem with installing it and everything I try to play works very well.
So there must be a specific raspberry pi problem with inputstream.adaptive according to me. I already had this impression in the past. 

Btw, are you aware of kodi portable version. See https://kodi.wiki/view/Portable_mode
It allows you to install multiple versions of kodi, also test versions, on one computer without interfering with each other. Very handy to test things.

**Comment by cometoluc** [comment] 2020-12-29 16:00
Thank yo michaelarnauts now it works again, thank you so much, have a happy newyear

You need to install the zip from https://github.com/add-ons/plugin.video.vtm.go/files/5747493/plugin.video.vtm.go-1.2.1-manifest-proxy-e7739cc.zip in Kodi. Use install by zip under Add-ons. This should fix the issue. A new release will be made soon.

**Comment by peno64** [comment] 2020-12-29 17:47
After installing the latest LibreElec RPI4 Matrix nightly build it all works fine now...

**Comment by cometoluc** [comment] 2020-12-29 23:11
@michaelarnauts : hello, i installed the plugin.video.vtm.go-1.2.1-manifest-proxy-e7739cc and now most things work again. The only problem i have is that there are no subtitles on movies or series. With the vtmgo program on my pc the subs are always there.

Btw. how can i post my answer in the post that you answered please? or is this the only way? best regards

**Closed** 2020-12-30 15:12 UTC
Labels: bug, inputstream-adaptive

**Comment by michaelarnauts** [comment] 2020-12-30 16:30
@cometoluc the subtitle issue was something else, but has been fixed in https://github.com/add-ons/plugin.video.vtm.go/pull/248

A new release has just been made, and will be made available soon in the kodi repo.

**Comment by cometoluc** [comment] 2021-01-01 19:35
@michaelarnauts : sorry for the ignorens but when that new release comes out is tht the file that has to be installed in addon repository-zip? And Where is kodi repo please? Happy new year

**Comment by michaelarnauts** [comment] 2021-01-01 21:55
> @michaelarnauts : sorry for the ignorens but when that new release comes out is tht the file that has to be installed in addon repository-zip? And Where is kodi repo please? Happy new year

Just install it according to the steps at https://github.com/add-ons/plugin.video.vtm.go/wiki/Installatie

You probably won't have to do anything, since installing it trough a zip will also cause it to be updated.

**Comment by dagwieers** [comment] 2021-01-02 15:01
Not on Kodi v19 apparently.
https://kodi.tv/article/refactoring-add-subsystem

**Comment by dirkronsmans** [comment] 2021-01-02 15:19
I wonder if u manually update from the repository it will auto update again as you change the origin.

**Comment by michaelarnauts** [comment] 2021-04-11 18:34
This has been fixed in the recently released versions of Inputstream Adaptive (both for Leia and Matrix), so the workaround can be disabled there.
