### ISSUE TITLE
Playback stops on ads

### ISSUE THREAD

**Issue by wimvdon** [add-ons/plugin.video.vtm.go#272] opened 2021-04-10 18:15 UTC
Playback stops when advertisements are supposed to be played. Black screen, sometimes fast forward can restart the stream but often not. I'm on Kodi 19 Matrix.
I'm also having similar issues starting a show, but usually the second attempt works.

**Comment by michaelarnauts** [comment] 2021-04-11 18:37
A new Inputstream Adaptive has been released with some fixed. It might help for your issues. On Android, it will auto-update, not sure about other environments.

For Matrix, latest version is 2.6.13, for Leia, this is 2.4.7.

**Comment by dagwieers** [comment] 2021-04-11 22:57
You need to restart Kodi Leia (v18) after you have update inoutstream.adaptive. I think they fixed this in Kodi Matrix (v19). But I am not 100% sure. A confirmation would be useful.

**Comment by wimvdon** [comment] 2021-04-14 17:19
I'm on the latest Inpurstream Adaptive version but I'm still experiencing the same issues: black screen on ads, playback fails, no error messages.

**Comment by michaelarnauts** [comment] 2021-04-15 06:15
If you're on the latest IA now, can you try to turn of the workaround in the expert settings to see if this improves things?

**Comment by badoneti** [comment] 2021-04-15 10:10
In libreelec 10 beta 1, kodi matrix (v19) I can only upgrade to Inputstream Adaptive 2.6.11.1 and will test with that and turned off the workaround. A first test was positive on the freeze. But the ad which typically freezes was not appearing. A longer test period is needed ;-) 
The problem is still there when you forward past an ad block, audio has gone. This only comes back when you let the ad block play through. 
Hope this feedback helps

**Comment by wimvdon** [comment] 2021-04-16 18:49
I'm experiencing the same issues after disabling the workaround in expert settings unfortunately.

**Comment by kengithub9** [comment] 2021-04-27 03:17
i have the same problems since i updated the input stream in coreelec with version 2.6.14.1. Everything worked with version 2.6.

**Comment by badoneti** [comment] 2021-05-22 11:27
In libreelec 10 beta 3, kodi matrix (v19.1) I needed to go back to Inputstream Adaptive 2.6.13.1 
(recent versions 2.6.14.1 and 2.6.15.1 block on some but not all ads and audio lost when fast forwarding over those problematic ads)
Tested with repo version of VTM GO 1.2.6 matrix

**Comment by michaelarnauts** [comment] 2021-05-22 15:27
A new IA has been released yesterday what fixes some issues related to this.

**Closed** 2021-05-25 09:25 UTC
